### ISSUE TITLE
[Suggestion] Add a button to teleport to the waypoint

### ISSUE THREAD

**Issue by stantios** [Lop010/coordinate-book#1]
Description: Basically the title. Maybe add a button the right of the coordinate box saying Teleport and it would use a command to teleport to it, which is how most minimap mods do it. For example, /tp @s x y z or something similiar to that and maybe add way in the config to change the command to something different but only except commands that start with /tp if that's possible.

**Comment by flysqu** [comment]
This will definitely be put in the upcoming features!
