### ISSUE TITLE
[Suggestion] Port to 1.19.2

### ISSUE THREAD

**Issue by stantios** [Lop010/coordinate-book#2]
Description: Basically the title. I think many people are still on 1.19.2 since there waiting for mods to update, since some mod devs are refusing to update to 1.19.3 until 1.20 comes out due to the changes and how hard it is to port a mod to 1.19.3 which is understandable. These might not be good points to make you port the mod, but please think about it.

**Comment by flysqu** [comment]
I will think about it but the problem is that porting to a newer version and porting to an older version is just the same in time and difficulty as i understand it.
