### ISSUE TITLE
[BUG] Incorrect text in the key bind menu

### ISSUE THREAD

**Issue by Dronatar** [Lop010/coordinate-book#3]
![ScreenShot_20230216071118](https://user-images.githubusercontent.com/35381259/219274299-89c4f0f6-a5de-41b1-a563-c3546d77ef33.png)

**Comment by flysqu** [comment]
![image](https://user-images.githubusercontent.com/98214547/219381505-b1d26279-38f4-4281-bfef-5cbd35a2db17.png)
Now fixed! 
Will release version 1.1 in about 30 minutes
