### ISSUE TITLE
[Suggestion] Update icon.png

### ISSUE THREAD

**Issue by Dronatar** [Lop010/coordinate-book#4]
Your mod icon with mod **Mod Menu**:
![ScreenShot_20230216072450](https://user-images.githubusercontent.com/35381259/219276271-05b5de5d-764c-4fce-b162-a2914b747eb4.png)
Here's what a fix with your project icon on modrinth would look like:
![ScreenShot_20230216073819](https://user-images.githubusercontent.com/35381259/219278022-4bc85bcc-af9c-4c33-a3ca-508f98ae8be5.png)

**Comment by flysqu** [comment]
It is now fixed will release version 1.1 in about 30 minutes
Thanks for the well written issues!
