### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Santiag09** [Lop010/coordinate-book#6]
Firstly, I click save but still need to click revert to save to see the saved cords again. Is this intentional? It'd be nice if it'd automatically show up in the cord book.

Secondly, when I list coordinates like 375,78,900 it splits it across the 3 boxes which is inconvenient 

Love the idea and would love this mod so much if you could fix these bugs. Thanks!

**Comment by flysqu** [comment]
For the first point i decided that i didnt want it to automatically load coordinates as i personally use it for 2b2t and other anarchy server so i dont accidently flash my coords. And i found that it was pretty annoying when it automatically did it. This is a opensource project and it would be a simple method call when the user changes pages so you could do it yourself.

For the second bug please show me some screenshots of this bug i havent had any bugs like that

**Comment by flysqu** [comment]
Its now fixed, I patched together a fix that replaces the comma with a "Q" temporarily while it stores it and loads it when it loads the data back. Will be released in a min
