### ISSUE TITLE
1.19.4 - 1.20.1 supports?

### ISSUE THREAD

**Issue by Scarlaid** [Lop010/coordinate-book#7]
The mod is nice, but it's on 1.19.3 only, and no, on 1.19.4 it would throw a `net.minecraft.class_148: mouseReleased event handler` crash report whenever pressing the save button

Hopefully there would be a 1.19.4 support (1.20.1 too if possible)

**Comment by flysqu** [comment]
Hey! I would really like to implement this but im not very motivated to update it as it didn't have that much success. If you have an modpack in the works and have had some success on modrinth then i'd definitely look into updating it

**Comment by flysqu** [comment]
Update! I am almost done with the 1.19.4 version. Will place it in a new branch when its completely done. Also the mod now makes a folder so it doesnt just throw everything into the main config folder
